services:
  - type: web
    name: tunnel-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        sync: false
      - key: RENDER
        value: "true"
